FROM mysql:8.0

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=${MYSQL_DATABASE}
ENV MYSQL_USER=${MYSQL_USER}
ENV MYSQL_PASSWORD=${MYSQL_PASSWORD}

COPY E8EksMysql/init.sql /docker-entrypoint-initdb.d/

RUN echo "[mysqld]\nlog_output=FILE\ngeneral_log=1\ngeneral_log_file=/var/log/mysql/general.log" >> /etc/mysql/my.cnf

EXPOSE 3306






